export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard.read',
  DASHBOARD_MANAGE: 'dashboard.manage',
  DASHBOARD_TRACKING: 'dashboard.tracking',
  GLOBAL_SEARCH: 'search.global',

  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE: 'users.manage',

  ADMINS_READ: 'admins.read',
  ADMINS_CREATE: 'admins.create',
  ADMINS_UPDATE: 'admins.update',
  ADMINS_DELETE: 'admins.delete',
  ADMINS_MANAGE: 'admins.manage',

  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  ROLES_MANAGE: 'roles.manage',

  PERMISSIONS_READ: 'permissions.read',
  PERMISSIONS_CREATE: 'permissions.create',
  PERMISSIONS_UPDATE: 'permissions.update',
  PERMISSIONS_DELETE: 'permissions.delete',
  PERMISSIONS_MANAGE: 'permissions.manage',

  COMPANIES_READ: 'companies.read',
  COMPANIES_CREATE: 'companies.create',
  COMPANIES_UPDATE: 'companies.update',
  COMPANIES_DELETE: 'companies.delete',
  COMPANIES_APPROVE: 'companies.approve',
  COMPANIES_REJECT: 'companies.reject',
  COMPANY_REQUESTS_READ: 'company_requests.read',
  COMPANY_REQUESTS_APPROVE: 'company_requests.approve',
  COMPANY_REQUESTS_REJECT: 'company_requests.reject',
  COMPANY_MEMBERS_READ: 'company_members.read',
  COMPANY_MEMBERS_MANAGE: 'company_members.manage',

  EMPLOYEES_READ: 'employees.read',
  EMPLOYEES_UPDATE: 'employees.update',
  EMPLOYEES_DELETE: 'employees.delete',
  EMPLOYEES_MANAGE: 'employees.manage',
  EMPLOYEE_CVS_READ: 'employee_cvs.read',
  EMPLOYEE_CVS_MANAGE: 'employee_cvs.manage',
  USER_RESUMES_READ: 'user_resumes.read',
  USER_RESUMES_MANAGE: 'user_resumes.manage',

  JOBS_READ: 'jobs.read',
  JOBS_CREATE: 'jobs.create',
  JOBS_UPDATE: 'jobs.update',
  JOBS_DELETE: 'jobs.delete',
  JOBS_APPROVE: 'jobs.approve',
  JOBS_REJECT: 'jobs.reject',
  JOB_APPROVALS_READ: 'job_approvals.read',
  JOB_APPROVALS_APPROVE: 'job_approvals.approve',
  JOB_APPROVALS_REJECT: 'job_approvals.reject',
  JOB_MATCHES_READ: 'job_matches.read',
  JOB_MATCHES_MANAGE: 'job_matches.manage',
  JOB_EMPLOYEE_MATCHES_READ: 'job_employee_matches.read',
  JOB_EMPLOYEE_MATCHES_MANAGE: 'job_employee_matches.manage',
  SAVED_JOBS_READ: 'saved_jobs.read',
  SHOWN_JOBS_READ: 'shown_jobs.read',
  OUTSIDE_APPLICATIONS_READ: 'outside_applications.read',

  APPLICATIONS_READ: 'applications.read',
  APPLICATIONS_UPDATE: 'applications.update',
  APPLICATIONS_DELETE: 'applications.delete',
  APPLICATIONS_MANAGE: 'applications.manage',
  APPLICATION_HISTORY_READ: 'application_history.read',

  INTERVIEWS_READ: 'interviews.read',
  INTERVIEWS_UPDATE: 'interviews.update',
  INTERVIEWS_DELETE: 'interviews.delete',
  INTERVIEWS_MANAGE: 'interviews.manage',

  INVITATIONS_READ: 'invitations.read',
  INVITATIONS_UPDATE: 'invitations.update',
  INVITATIONS_DELETE: 'invitations.delete',
  INVITATIONS_MANAGE: 'invitations.manage',

  TALENT_REQUESTS_READ: 'talent_requests.read',
  TALENT_REQUESTS_UPDATE: 'talent_requests.update',
  TALENT_REQUESTS_MANAGE: 'talent_requests.manage',

  REPORTS_READ: 'reports.read',
  REPORTS_UPDATE: 'reports.update',
  REPORTS_DELETE: 'reports.delete',
  REPORTS_MANAGE: 'reports.manage',

  REVIEWS_READ: 'reviews.read',
  REVIEWS_UPDATE: 'reviews.update',
  REVIEWS_DELETE: 'reviews.delete',
  REVIEWS_MANAGE: 'reviews.manage',
  RATINGS_READ: 'ratings.read',
  RATINGS_MANAGE: 'ratings.manage',
  COMPANY_REVIEWS_READ: 'company_reviews.read',
  COMPANY_REVIEWS_MANAGE: 'company_reviews.manage',

  LOOKUPS_READ: 'lookups.read',
  LOOKUPS_MANAGE: 'lookups.manage',
  COUNTRIES_MANAGE: 'countries.manage',
  CURRENCIES_MANAGE: 'currencies.manage',
  LANGUAGES_MANAGE: 'languages.manage',
  SKILLS_MANAGE: 'skills.manage',
  INDUSTRIES_MANAGE: 'industries.manage',
  EDUCATION_LEVELS_MANAGE: 'education_levels.manage',
  EXPERIENCE_LEVELS_MANAGE: 'experience_levels.manage',
  JOB_NAMES_MANAGE: 'job_names.manage',
  JOB_TYPES_MANAGE: 'job_types.manage',
  JOB_SERVICES_MANAGE: 'job_services.manage',
  JOB_SALARIES_MANAGE: 'job_salaries.manage',
  WORK_TIMES_MANAGE: 'work_times.manage',
  WORK_MODES_MANAGE: 'work_modes.manage',
  WORK_LOCATIONS_MANAGE: 'work_locations.manage',

  CONTENT_READ: 'content.read',
  CONTENT_MANAGE: 'content.manage',
  PAGES_MANAGE: 'pages.manage',
  BANNERS_MANAGE: 'banners.manage',
  KEYWORDS_MANAGE: 'keywords.manage',
  CV_TEMPLATES_MANAGE: 'cv_templates.manage',
  COLORS_MANAGE: 'colors.manage',
  FONTS_MANAGE: 'fonts.manage',
  RESUMES_MANAGE: 'resumes.manage',

  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_SEND: 'notifications.send',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  FCM_TOKENS_READ: 'fcm_tokens.read',

  SUBSCRIPTIONS_READ: 'subscriptions.read',
  SUBSCRIPTIONS_CREATE: 'subscriptions.create',
  SUBSCRIPTIONS_UPDATE: 'subscriptions.update',
  SUBSCRIPTIONS_DELETE: 'subscriptions.delete',
  SUBSCRIPTIONS_MANAGE: 'subscriptions.manage',
  SUBSCRIPTION_PLANS_READ: 'subscription_plans.read',
  SUBSCRIPTION_PLANS_MANAGE: 'subscription_plans.manage',
  COMPANY_SUBSCRIPTIONS_READ: 'company_subscriptions.read',
  COMPANY_SUBSCRIPTIONS_ASSIGN: 'company_subscriptions.assign',
  COMPANY_SUBSCRIPTIONS_MANAGE: 'company_subscriptions.manage',

  SETTINGS_READ: 'settings.read',
  SETTINGS_MANAGE: 'settings.manage',
  SEARCH_HISTORY_READ: 'search_history.read',
  IMPORT_MANAGE: 'import.manage',
};

export const ALL_DASH_PERMISSIONS = Object.values(PERMISSIONS);
