import express from 'express';
import AuthRote from './AuthRote.js';
import CompanyRote from './CompanyRote.js';
import HelperRote from './HelperRote.js';
import JobRote from './JobRote.js';
import EmployeeRote from './EmployeeRote.js';
import JobInformationRote from './JobInformationRote.js';
import ApplyingJobRote from './ApplyingJobRote.js';
import JobResultRote from './JobResultRote.js';
import JobProfileRote from './JobProfileRote.js';
import CompanyProfileRote from './CompanyProfileRote.js';
import FcmRote from './FcmRote.js';
import HandleAppliedJobRote from './HandleAppliedJobRote.js';
import KeywordRote from './KeywordRote.js';
import bannerRote from './bannerRote.js';
import AppUserOverviewRote from './AppUserOverviewRote.js';
import pageRote from './pageRote.js';
import NotificationRote from './NotificationRote.js';
import CampusRote from './CampusRote.js';
import MeRote from './MeRote.js';
import CareerPassportRote from './CareerPassportRote.js';
import GlobalRote from './GlobalRote.js';

const router = express.Router();
router.use('/me', MeRote);
router.use('/career-passport', CareerPassportRote);
router.use('/global', GlobalRote);
router.use('/auth', AuthRote);
router.use('/company', CompanyRote);
router.use('/helper', HelperRote);
router.use('/job', JobRote);
router.use('/employee', EmployeeRote);
router.use('/job-information', JobInformationRote);
router.use('/applying-job', ApplyingJobRote);
router.use('/job-result', JobResultRote);
router.use('/job-profile', JobProfileRote);
router.use('/company-jobs-profile', CompanyProfileRote);
router.use('/fcm', FcmRote);
router.use('/handle-applied-job', HandleAppliedJobRote);
router.use('/keyword', KeywordRote);
router.use('/banner', bannerRote);
router.use('/app/dashboard', AppUserOverviewRote);
router.use('/page', pageRote);
router.use('/notifications', NotificationRote);
router.use('/notification', NotificationRote);
router.use('/campus', CampusRote);

export default router;
