import dotenv from "dotenv";
import { IndustryModel } from "../models/index.js";
import normalizeArabicKeyword from "../helper/normalizeArabicKeyword.js";

dotenv.config();

export const seedIndustries = async () => {
  try {
    const industries = [
      {
        key: "information_technology",
        title_ar: "تكنولوجيا المعلومات",
        title_en: "Information Technology",
        keywords_ar: [
          "تكنولوجيا المعلومات",
          "تقنية المعلومات",
          "اي تي",
          "برمجة",
          "تطوير برمجيات",
          "سوفت وير",
          "تقنية",
        ],
        keywords_en: [
          "information technology",
          "it",
          "software",
          "software development",
          "technology",
          "tech",
          "programming",
        ],
      },
      {
        key: "healthcare",
        title_ar: "الرعاية الصحية",
        title_en: "Healthcare",
        keywords_ar: [
          "صحة",
          "رعاية صحية",
          "مستشفى",
          "عيادات",
          "طبي",
          "طب",
          "تمريض",
        ],
        keywords_en: [
          "healthcare",
          "health",
          "medical",
          "hospital",
          "clinic",
          "nursing",
          "medicine",
        ],
      },
      {
        key: "education",
        title_ar: "التعليم والتدريب",
        title_en: "Education & Training",
        keywords_ar: [
          "تعليم",
          "تدريب",
          "مدارس",
          "جامعة",
          "معاهد",
          "تعلم",
          "اكاديمي",
        ],
        keywords_en: [
          "education",
          "training",
          "school",
          "university",
          "academy",
          "learning",
          "teaching",
        ],
      },
      {
        key: "finance_banking",
        title_ar: "المالية والبنوك",
        title_en: "Finance & Banking",
        keywords_ar: [
          "مالية",
          "بنوك",
          "مصارف",
          "محاسبة",
          "استثمار",
          "تأمين",
          "تمويل",
        ],
        keywords_en: [
          "finance",
          "banking",
          "bank",
          "accounting",
          "investment",
          "insurance",
          "funding",
        ],
      },
      {
        key: "marketing_advertising",
        title_ar: "التسويق والإعلان",
        title_en: "Marketing & Advertising",
        keywords_ar: [
          "تسويق",
          "اعلان",
          "إعلانات",
          "ديجيتال ماركتنج",
          "سوشيال ميديا",
          "علامات تجارية",
        ],
        keywords_en: [
          "marketing",
          "advertising",
          "digital marketing",
          "social media",
          "branding",
          "ads",
        ],
      },
      {
        key: "sales_retail",
        title_ar: "المبيعات والتجزئة",
        title_en: "Sales & Retail",
        keywords_ar: [
          "مبيعات",
          "بيع",
          "تجزئة",
          "متاجر",
          "محلات",
          "كاشير",
          "خدمة عملاء",
        ],
        keywords_en: [
          "sales",
          "retail",
          "store",
          "shop",
          "cashier",
          "customer service",
        ],
      },
      {
        key: "manufacturing",
        title_ar: "الصناعة والتصنيع",
        title_en: "Manufacturing",
        keywords_ar: [
          "تصنيع",
          "صناعة",
          "مصانع",
          "انتاج",
          "خط انتاج",
          "تشغيل",
        ],
        keywords_en: [
          "manufacturing",
          "factory",
          "production",
          "industrial",
          "operations",
        ],
      },
      {
        key: "construction_engineering",
        title_ar: "البناء والهندسة",
        title_en: "Construction & Engineering",
        keywords_ar: [
          "بناء",
          "مقاولات",
          "هندسة",
          "مدني",
          "معماري",
          "انشاءات",
          "مشاريع",
        ],
        keywords_en: [
          "construction",
          "engineering",
          "civil engineering",
          "architecture",
          "contracting",
          "projects",
        ],
      },
      {
        key: "real_estate",
        title_ar: "العقارات",
        title_en: "Real Estate",
        keywords_ar: [
          "عقارات",
          "تطوير عقاري",
          "بيع عقارات",
          "تأجير",
          "وساطة عقارية",
        ],
        keywords_en: [
          "real estate",
          "property",
          "properties",
          "brokerage",
          "leasing",
        ],
      },
      {
        key: "hospitality_tourism",
        title_ar: "الضيافة والسياحة",
        title_en: "Hospitality & Tourism",
        keywords_ar: [
          "ضيافة",
          "سياحة",
          "فنادق",
          "مطاعم",
          "سفر",
          "حجوزات",
        ],
        keywords_en: [
          "hospitality",
          "tourism",
          "hotel",
          "restaurant",
          "travel",
          "booking",
        ],
      },
      {
        key: "food_beverage",
        title_ar: "الأغذية والمشروبات",
        title_en: "Food & Beverage",
        keywords_ar: [
          "اغذية",
          "مشروبات",
          "مطاعم",
          "كافيه",
          "مأكولات",
          "تغذية",
        ],
        keywords_en: [
          "food",
          "beverage",
          "restaurant",
          "cafe",
          "catering",
          "nutrition",
        ],
      },
      {
        key: "logistics_transportation",
        title_ar: "النقل والخدمات اللوجستية",
        title_en: "Logistics & Transportation",
        keywords_ar: [
          "نقل",
          "لوجستيات",
          "شحن",
          "توصيل",
          "مستودعات",
          "سلاسل امداد",
        ],
        keywords_en: [
          "logistics",
          "transportation",
          "shipping",
          "delivery",
          "warehouse",
          "supply chain",
        ],
      },
      {
        key: "telecommunications",
        title_ar: "الاتصالات",
        title_en: "Telecommunications",
        keywords_ar: [
          "اتصالات",
          "شبكات",
          "مزود خدمة",
          "انترنت",
          "هاتف",
          "تيليكوم",
        ],
        keywords_en: [
          "telecommunications",
          "telecom",
          "network",
          "internet",
          "mobile",
          "isp",
        ],
      },
      {
        key: "media_entertainment",
        title_ar: "الإعلام والترفيه",
        title_en: "Media & Entertainment",
        keywords_ar: [
          "اعلام",
          "ترفيه",
          "انتاج",
          "تصوير",
          "مونتاج",
          "قنوات",
          "محتوى",
        ],
        keywords_en: [
          "media",
          "entertainment",
          "production",
          "content",
          "video",
          "editing",
          "broadcasting",
        ],
      },
      {
        key: "legal_services",
        title_ar: "الخدمات القانونية",
        title_en: "Legal Services",
        keywords_ar: [
          "قانون",
          "محاماة",
          "استشارات قانونية",
          "عقود",
          "قضايا",
        ],
        keywords_en: [
          "legal",
          "law",
          "lawyer",
          "attorney",
          "contracts",
          "legal services",
        ],
      },
      {
        key: "human_resources",
        title_ar: "الموارد البشرية والتوظيف",
        title_en: "Human Resources & Recruitment",
        keywords_ar: [
          "موارد بشرية",
          "توظيف",
          "اتش ار",
          "استقطاب",
          "رواتب",
          "شؤون موظفين",
        ],
        keywords_en: [
          "human resources",
          "hr",
          "recruitment",
          "hiring",
          "talent acquisition",
          "payroll",
        ],
      },
      {
        key: "consulting",
        title_ar: "الاستشارات",
        title_en: "Consulting",
        keywords_ar: [
          "استشارات",
          "استشاري",
          "ادارة",
          "تحليل اعمال",
          "تطوير اعمال",
        ],
        keywords_en: [
          "consulting",
          "consultancy",
          "advisor",
          "business consulting",
          "management consulting",
        ],
      },
      {
        key: "government_public_sector",
        title_ar: "الحكومة والقطاع العام",
        title_en: "Government & Public Sector",
        keywords_ar: [
          "حكومة",
          "قطاع عام",
          "بلدية",
          "مؤسسة حكومية",
          "خدمات عامة",
        ],
        keywords_en: [
          "government",
          "public sector",
          "municipality",
          "public services",
        ],
      },
      {
        key: "non_profit",
        title_ar: "المنظمات غير الربحية",
        title_en: "Non-Profit Organizations",
        keywords_ar: [
          "منظمة",
          "غير ربحي",
          "جمعية",
          "منظمات انسانية",
          "تطوع",
        ],
        keywords_en: [
          "non profit",
          "ngo",
          "charity",
          "organization",
          "volunteering",
        ],
      },
      {
        key: "energy_utilities",
        title_ar: "الطاقة والمرافق",
        title_en: "Energy & Utilities",
        keywords_ar: [
          "طاقة",
          "كهرباء",
          "مياه",
          "غاز",
          "نفط",
          "طاقة متجددة",
        ],
        keywords_en: [
          "energy",
          "utilities",
          "electricity",
          "water",
          "gas",
          "oil",
          "renewable energy",
        ],
      },
      {
        key: "agriculture",
        title_ar: "الزراعة",
        title_en: "Agriculture",
        keywords_ar: [
          "زراعة",
          "مزارع",
          "انتاج زراعي",
          "اغذية زراعية",
          "ثروة حيوانية",
        ],
        keywords_en: [
          "agriculture",
          "farming",
          "farm",
          "agribusiness",
          "livestock",
        ],
      },
      {
        key: "automotive",
        title_ar: "السيارات",
        title_en: "Automotive",
        keywords_ar: [
          "سيارات",
          "مركبات",
          "صيانة سيارات",
          "قطع غيار",
          "معارض سيارات",
        ],
        keywords_en: [
          "automotive",
          "cars",
          "vehicles",
          "auto repair",
          "spare parts",
        ],
      },
      {
        key: "pharmaceuticals",
        title_ar: "الأدوية والصناعات الدوائية",
        title_en: "Pharmaceuticals",
        keywords_ar: [
          "ادوية",
          "صيدلة",
          "صناعات دوائية",
          "مختبرات",
          "مستلزمات طبية",
        ],
        keywords_en: [
          "pharmaceuticals",
          "pharmacy",
          "medicine",
          "medical supplies",
          "laboratory",
        ],
      },
      {
        key: "ecommerce",
        title_ar: "التجارة الإلكترونية",
        title_en: "E-Commerce",
        keywords_ar: [
          "تجارة الكترونية",
          "متجر الكتروني",
          "اونلاين",
          "بيع اونلاين",
          "اي كومرس",
        ],
        keywords_en: [
          "ecommerce",
          "e-commerce",
          "online store",
          "online shopping",
          "marketplace",
        ],
      },
      {
        key: "security_safety",
        title_ar: "الأمن والسلامة",
        title_en: "Security & Safety",
        keywords_ar: [
          "امن",
          "سلامة",
          "حراسة",
          "كاميرات",
          "امن صناعي",
          "حماية",
        ],
        keywords_en: [
          "security",
          "safety",
          "guarding",
          "surveillance",
          "protection",
        ],
      },
      {
        key: "design_creative",
        title_ar: "التصميم والإبداع",
        title_en: "Design & Creative",
        keywords_ar: [
          "تصميم",
          "جرافيك",
          "ابداع",
          "هوية بصرية",
          "تصميم واجهات",
          "موشن",
        ],
        keywords_en: [
          "design",
          "creative",
          "graphic design",
          "ui ux",
          "branding",
          "motion",
        ],
      },
      {
        key: "other",
        title_ar: "أخرى",
        title_en: "Other",
        keywords_ar: [
          "اخرى",
          "غير محدد",
          "متنوع",
        ],
        keywords_en: [
          "other",
          "miscellaneous",
          "general",
        ],
      },
    ];

    for (const industry of industries) {
      await IndustryModel.updateOne(
        {
          key: industry.key,
        },
        {
          $set: {
            key: industry.key,
            title_ar: industry.title_ar,
            title_en: industry.title_en,
            keywords_ar: industry.keywords_ar.map(normalizeArabicKeyword),
            keywords_en: industry.keywords_en.map((item) =>
              String(item || "").trim().toLowerCase()
            ),
            is_active: true,
            is_system: true,
          },
        },
        {
          upsert: true,
        }
      );
    }

    console.log("✅ Industries seeded successfully");
  } catch (error) {
    console.error("❌ Industries seeder error:", error);
    throw error;
  }
};