import dotenv from "dotenv";
import { WorkModeModel } from "../models/index.js";
import normalizeArabicKeyword from "../helper/normalizeArabicKeyword.js";

dotenv.config();

 const seedWorkModes = async () => {
 try {
  const workModes = [
   {
    key: "onsite",
    title_ar: "ضمن الشركة",
    title_en: "On-site",
    keywords_ar: ["ضمن الشركة", "داخل الشركة", "في المكتب", "حضوري", "مكتبي", "دوام حضوري", "من مقر الشركة"],
    keywords_en: ["onsite", "on site", "office", "in office", "office based", "work from office", "in person"],
    icon: "building",
    sort_order: 1,
   },
   {
    key: "remote",
    title_ar: "عن بعد",
    title_en: "Remote",
    keywords_ar: ["عن بعد", "ريموت", "اونلاين", "اون لاين", "من المنزل", "عمل من المنزل", "عمل عبر الانترنت", "من اي مكان"],
    keywords_en: ["remote", "remote work", "work from home", "wfh", "online", "virtual", "work from anywhere"],
    icon: "wifi",
    sort_order: 2,
   },
   {
    key: "hybrid",
    title_ar: "هجين",
    title_en: "Hybrid",
    keywords_ar: ["هجين", "مختلط", "حضوري وعن بعد", "دوام مختلط", "جزء من المنزل", "جزء من الشركة"],
    keywords_en: ["hybrid", "hybrid work", "mixed", "part remote", "part onsite", "office and remote"],
    icon: "shuffle",
    sort_order: 3,
   },
   {
    key: "field",
    title_ar: "ميداني",
    title_en: "Field-based",
    keywords_ar: ["ميداني", "عمل ميداني", "زيارات", "مندوب", "خارج المكتب", "تنقل", "في الموقع"],
    keywords_en: ["field", "field based", "field work", "site visits", "outside office", "on location"],
    icon: "map-pin",
    sort_order: 4,
   },
   {
    key: "client_site",
    title_ar: "ضمن موقع العميل",
    title_en: "Client Site",
    keywords_ar: ["موقع العميل", "عند العميل", "ضمن موقع العميل", "داخل موقع العميل"],
    keywords_en: ["client site", "customer site", "onsite client", "at client location"],
    icon: "briefcase",
    sort_order: 5,
   },
   {
    key: "travel_based",
    title_ar: "يعتمد على السفر",
    title_en: "Travel-based",
    keywords_ar: ["سفر", "يعتمد على السفر", "تنقل دائم", "رحلات عمل", "سفر عمل"],
    keywords_en: ["travel based", "travel required", "business travel", "frequent travel", "traveling role"],
    icon: "plane",
    sort_order: 6,
   },
   {
    key: "mobile",
    title_ar: "متنقل",
    title_en: "Mobile",
    keywords_ar: ["متنقل", "عمل متنقل", "تنقل", "بدون مكتب ثابت", "من عدة مواقع"],
    keywords_en: ["mobile", "mobile work", "mobile role", "no fixed office", "multiple locations"],
    icon: "navigation",
    sort_order: 7,
   },
   {
    key: "distributed",
    title_ar: "فريق موزع",
    title_en: "Distributed Team",
    keywords_ar: ["فريق موزع", "موزع", "فريق عالمي", "فريق عن بعد"],
    keywords_en: ["distributed", "distributed team", "global team", "remote team"],
    icon: "users",
    sort_order: 8,
   },
   {
    key: "flexible_location",
    title_ar: "مكان عمل مرن",
    title_en: "Flexible Location",
    keywords_ar: ["مكان مرن", "مرونة مكان العمل", "عمل مرن", "اختيار مكان العمل"],
    keywords_en: ["flexible location", "location flexible", "flexible workplace", "choose location"],
    icon: "globe",
    sort_order: 9,
   },
   {
    key: "coworking",
    title_ar: "مساحة عمل مشتركة",
    title_en: "Coworking Space",
    keywords_ar: ["مساحة عمل مشتركة", "كو ووركينغ", "مكتب مشترك", "مساحات عمل"],
    keywords_en: ["coworking", "co working", "coworking space", "shared office"],
    icon: "layout-dashboard",
    sort_order: 10,
   },
   {
    key: "home_based",
    title_ar: "من المنزل",
    title_en: "Home-based",
    keywords_ar: ["من المنزل", "عمل منزلي", "دوام من المنزل", "العمل من البيت"],
    keywords_en: ["home based", "home office", "work from home", "home working"],
    icon: "home",
    sort_order: 11,
   },
   {
    key: "remote_first",
    title_ar: "عن بعد اولا",
    title_en: "Remote-first",
    keywords_ar: ["عن بعد اولا", "ريموت اولا", "الشركة تعتمد العمل عن بعد", "العمل الاساسي عن بعد"],
    keywords_en: ["remote first", "remote-first", "remote company", "remote by default"],
    icon: "cloud",
    sort_order: 12,
   },
   {
    key: "office_first",
    title_ar: "ضمن الشركة غالبا",
    title_en: "Office-first",
    keywords_ar: ["ضمن الشركة غالبا", "حضوري غالبا", "المكتب هو الاساس", "العمل الاساسي من المكتب"],
    keywords_en: ["office first", "office-first", "office by default", "mostly office"],
    icon: "building-2",
    sort_order: 13,
   },
   {
    key: "hybrid_remote_first",
    title_ar: "هجين مع افضلية عن بعد",
    title_en: "Hybrid Remote-first",
    keywords_ar: ["هجين عن بعد", "هجين مع افضلية عن بعد", "غالبا عن بعد", "ريموت غالبا"],
    keywords_en: ["hybrid remote first", "mostly remote", "remote leaning hybrid"],
    icon: "monitor-up",
    sort_order: 14,
   },
   {
    key: "hybrid_office_first",
    title_ar: "هجين مع افضلية الحضور",
    title_en: "Hybrid Office-first",
    keywords_ar: ["هجين حضوري", "هجين مع افضلية الحضور", "غالبا في المكتب", "حضوري غالبا"],
    keywords_en: ["hybrid office first", "mostly office", "office leaning hybrid"],
    icon: "building",
    sort_order: 15,
   },
   {
    key: "rotational",
    title_ar: "تناوبي",
    title_en: "Rotational",
    keywords_ar: ["تناوبي", "نظام تناوبي", "دوام تناوبي", "تبديل مواقع"],
    keywords_en: ["rotational", "rotation", "rotational work", "rotating locations"],
    icon: "repeat",
    sort_order: 16,
   },
   {
    key: "on_call",
    title_ar: "عند الطلب",
    title_en: "On-call",
    keywords_ar: ["عند الطلب", "استدعاء", "حسب الحاجة", "متاح عند الطلب"],
    keywords_en: ["on call", "on-call", "call based", "as needed"],
    icon: "phone-call",
    sort_order: 17,
   },
   {
    key: "site_based",
    title_ar: "ضمن موقع العمل",
    title_en: "Site-based",
    keywords_ar: ["موقع العمل", "ضمن الموقع", "في موقع العمل", "موقع المشروع"],
    keywords_en: ["site based", "work site", "project site", "job site"],
    icon: "hard-hat",
    sort_order: 18,
   },
   {
    key: "branch_based",
    title_ar: "ضمن فرع محدد",
    title_en: "Branch-based",
    keywords_ar: ["فرع", "ضمن فرع", "فرع محدد", "مقر فرعي"],
    keywords_en: ["branch based", "branch office", "specific branch", "local branch"],
    icon: "store",
    sort_order: 19,
   },
   {
    key: "multi_branch",
    title_ar: "بين عدة فروع",
    title_en: "Multi-branch",
    keywords_ar: ["عدة فروع", "بين الفروع", "فروع متعددة", "تنقل بين الفروع"],
    keywords_en: ["multi branch", "multiple branches", "between branches", "branch rotation"],
    icon: "git-branch",
    sort_order: 20,
   },
   {
    key: "factory_based",
    title_ar: "ضمن المصنع",
    title_en: "Factory-based",
    keywords_ar: ["مصنع", "ضمن المصنع", "عمل صناعي", "خط انتاج"],
    keywords_en: ["factory based", "factory", "plant based", "manufacturing site"],
    icon: "factory",
    sort_order: 21,
   },
   {
    key: "warehouse_based",
    title_ar: "ضمن المستودع",
    title_en: "Warehouse-based",
    keywords_ar: ["مستودع", "ضمن المستودع", "مخزن", "مخازن", "عمل مستودعات"],
    keywords_en: ["warehouse based", "warehouse", "storage facility", "logistics site"],
    icon: "warehouse",
    sort_order: 22,
   },
   {
    key: "retail_store",
    title_ar: "ضمن متجر",
    title_en: "Retail Store",
    keywords_ar: ["متجر", "محل", "ضمن المتجر", "بيع مباشر", "تجزئة"],
    keywords_en: ["retail store", "store based", "shop", "in store", "retail location"],
    icon: "shopping-bag",
    sort_order: 23,
   },
   {
    key: "restaurant_based",
    title_ar: "ضمن مطعم",
    title_en: "Restaurant-based",
    keywords_ar: ["مطعم", "ضمن مطعم", "كافيه", "مقهى", "ضيافة"],
    keywords_en: ["restaurant based", "restaurant", "cafe", "hospitality location"],
    icon: "utensils",
    sort_order: 24,
   },
   {
    key: "hospital_based",
    title_ar: "ضمن منشاة صحية",
    title_en: "Healthcare Facility-based",
    keywords_ar: ["مشفى", "مستشفى", "عيادة", "مركز صحي", "منشاة صحية"],
    keywords_en: ["hospital based", "clinic based", "healthcare facility", "medical center"],
    icon: "hospital",
    sort_order: 25,
   },
   {
    key: "school_based",
    title_ar: "ضمن منشاة تعليمية",
    title_en: "Education Facility-based",
    keywords_ar: ["مدرسة", "جامعة", "معهد", "منشاة تعليمية", "مركز تعليمي"],
    keywords_en: ["school based", "university based", "education facility", "campus based"],
    icon: "graduation-cap",
    sort_order: 26,
   },
   {
    key: "campus_based",
    title_ar: "ضمن الحرم الجامعي",
    title_en: "Campus-based",
    keywords_ar: ["حرم جامعي", "داخل الجامعة", "داخل الكلية", "كامبوس"],
    keywords_en: ["campus based", "campus", "university campus", "college campus"],
    icon: "landmark",
    sort_order: 27,
   },
   {
    key: "offshore",
    title_ar: "خارجي",
    title_en: "Offshore",
    keywords_ar: ["خارجي", "اوف شور", "عمل خارجي", "فريق خارجي"],
    keywords_en: ["offshore", "offshore work", "offshore team", "overseas work"],
    icon: "ship",
    sort_order: 28,
   },
   {
    key: "nearshore",
    title_ar: "قريب جغرافيا",
    title_en: "Nearshore",
    keywords_ar: ["نير شور", "قريب جغرافيا", "فريق قريب", "دولة قريبة"],
    keywords_en: ["nearshore", "nearshore work", "nearshore team", "nearby country"],
    icon: "map",
    sort_order: 29,
   },
   {
    key: "cross_border_remote",
    title_ar: "عن بعد عبر الحدود",
    title_en: "Cross-border Remote",
    keywords_ar: ["عن بعد دولي", "ريموت دولي", "عبر الحدود", "عمل مع شركة خارجية"],
    keywords_en: ["cross border remote", "international remote", "global remote", "remote abroad"],
    icon: "earth",
    sort_order: 30,
   },
   {
    key: "expatriate",
    title_ar: "اغتراب للعمل",
    title_en: "Expatriate",
    keywords_ar: ["اغتراب", "عمل خارج البلد", "انتقال لدولة اخرى", "اقامة عمل"],
    keywords_en: ["expatriate", "expat", "relocation abroad", "work abroad"],
    icon: "passport",
    sort_order: 31,
   },
   {
    key: "relocation_required",
    title_ar: "يتطلب الانتقال",
    title_en: "Relocation Required",
    keywords_ar: ["يتطلب الانتقال", "نقل سكن", "الانتقال للمدينة", "الانتقال للعمل"],
    keywords_en: ["relocation required", "must relocate", "relocate", "move required"],
    icon: "move-right",
    sort_order: 32,
   },
   {
    key: "no_relocation",
    title_ar: "لا يتطلب الانتقال",
    title_en: "No Relocation",
    keywords_ar: ["لا يتطلب الانتقال", "بدون انتقال", "لا حاجة لنقل السكن"],
    keywords_en: ["no relocation", "relocation not required", "no move required"],
    icon: "map-pinned",
    sort_order: 33,
   },
   {
    key: "seasonal_location",
    title_ar: "موقع موسمي",
    title_en: "Seasonal Location",
    keywords_ar: ["موسمي", "موقع موسمي", "حسب الموسم", "عمل موسمي"],
    keywords_en: ["seasonal location", "seasonal work", "season based", "temporary location"],
    icon: "calendar-days",
    sort_order: 34,
   },
   {
    key: "temporary_remote",
    title_ar: "عن بعد مؤقت",
    title_en: "Temporary Remote",
    keywords_ar: ["عن بعد مؤقت", "ريموت مؤقت", "مؤقتا عن بعد"],
    keywords_en: ["temporary remote", "remote temporarily", "temporarily remote"],
    icon: "timer",
    sort_order: 35,
   },
   {
    key: "hot_desk",
    title_ar: "مكتب مشترك داخلي",
    title_en: "Hot Desk",
    keywords_ar: ["مكتب مشترك", "مكتب غير ثابت", "هات ديسك", "مقعد عمل مشترك"],
    keywords_en: ["hot desk", "hot desking", "shared desk", "non assigned desk"],
    icon: "panel-top",
    sort_order: 36,
   },
   {
    key: "hub_based",
    title_ar: "ضمن مركز عمل",
    title_en: "Hub-based",
    keywords_ar: ["مركز عمل", "ضمن مركز", "هاب", "مركز اقليمي"],
    keywords_en: ["hub based", "work hub", "regional hub", "office hub"],
    icon: "network",
    sort_order: 37,
   },
   {
    key: "satellite_office",
    title_ar: "مكتب فرعي صغير",
    title_en: "Satellite Office",
    keywords_ar: ["مكتب فرعي", "مكتب صغير", "مكتب تابع", "فرع صغير"],
    keywords_en: ["satellite office", "small office", "local office", "sub office"],
    icon: "radio-tower",
    sort_order: 38,
   },
  ];

  for (const workMode of workModes) {
   await WorkModeModel.updateOne(
    { key: workMode.key },
    {
     $set: {
      key: workMode.key,

      title_ar: workMode.title_ar,
      title_en: workMode.title_en,
      keywords_ar: workMode.keywords_ar.map(normalizeArabicKeyword),
      keywords_en: workMode.keywords_en,

      icon: workMode.icon,
      sort_order: workMode.sort_order,

      is_active: true,
      is_system: true,
     },
    },
    { upsert: true }
   );
  }

  console.log("✅ Work modes seeded successfully");
 } catch (error) {
  console.error("❌ Work modes seeder error:", error);
  throw error;
 }
};
export {seedWorkModes}