import assert from "node:assert/strict";
import listEndpoints from "express-list-endpoints";
import app from "../app.js";

const endpoints = listEndpoints(app);
const endpointByPath = new Map(endpoints.map((endpoint) => [endpoint.path, endpoint]));

const requiredEndpoints = [
  ["POST", "/user/v1/auth/register"],
  ["POST", "/user/v1/auth/campus/register"],
  ["POST", "/user/v1/auth/login"],
  ["POST", "/user/v1/auth/logout"],
  ["POST", "/user/v1/auth/passcode-verify"],
  ["POST", "/user/v1/auth/forgot-password"],
  ["POST", "/user/v1/auth/passcode-forgot-password"],
  ["POST", "/user/v1/auth/resetPassword"],
  ["POST", "/user/v1/auth/update-profile"],

  ["GET", "/user/v1/me/contexts"],
  ["POST", "/user/v1/me/active-context"],
  ["GET", "/user/v1/me/permissions"],

  ["GET", "/user/v1/career-passport"],
  ["PUT", "/user/v1/career-passport"],
  ["POST", "/user/v1/career-passport/share"],
  ["GET", "/user/v1/career-passport/share/:token"],
  ["POST", "/ai/v1/career-passport/score"],

  ["POST", "/analytics/v1/events"],
  ["POST", "/analytics/v1/track"],

  ["POST", "/ai/v1/translate/job/:jobId"],
  ["POST", "/ai/v1/translate/cv"],
  ["PUT", "/jobs/v1/:jobId/translations/:lang"],
  ["PUT", "/user/v1/cv/translations/:lang"],

  ["POST", "/trust/v1/jobs/:jobId/score"],
  ["POST", "/trust/v1/jobs/:jobId/report"],

  ["GET", "/user/v1/global/countries"],
  ["GET", "/user/v1/global/cities"],
  ["GET", "/user/v1/global/currencies"],
  ["GET", "/user/v1/global/work-modes"],

  ["GET", "/campus/v1/universities"],
  ["GET", "/campus/v1/universities/:id/campuses"],
  ["GET", "/campus/v1/student-verifications/me"],
  ["POST", "/campus/v1/student-verifications"],
  ["POST", "/campus/v1/student-verifications/:id/resubmit"],
  ["POST", "/campus/v1/verification/start"],
  ["POST", "/campus/v1/verification/confirm-email"],
  ["POST", "/campus/v1/verification/upload-document"],
  ["GET", "/campus/v1/admin/verifications"],
  ["POST", "/campus/v1/admin/verifications/:id/approve"],
  ["POST", "/campus/v1/admin/verifications/:id/reject"],
  ["POST", "/campus/v1/admin/verifications/:id/request-info"],

  ["GET", "/university/v1/dashboard"],
  ["GET", "/university/v1/dashboard/overview"],
  ["GET", "/university/v1/overview"],
  ["GET", "/university/v1/students"],
  ["GET", "/university/v1/students/:studentId/career-passport"],
  ["GET", "/university/v1/verifications"],
  ["POST", "/university/v1/verifications/:id/approve"],
  ["POST", "/university/v1/verifications/:id/reject"],
  ["POST", "/university/v1/verifications/:id/request-info"],
  ["GET", "/university/v1/analytics/employability"],
  ["GET", "/university/v1/reports/outcomes"],
  ["GET", "/university/v1/partners"],
  ["GET", "/university/v1/employer-partners"],
  ["GET", "/university/v1/opportunities"],
  ["POST", "/university/v1/opportunities"],

  ["GET", "/user/v1/helper/languages"],
  ["GET", "/user/v1/helper/work-mode"],
  ["GET", "/user/v1/helper/job-types"],
  ["GET", "/user/v1/helper/job-time"],
  ["GET", "/user/v1/helper/cities"],
  ["GET", "/user/v1/helper/countries"],

  ["GET", "/user/v1/job/get"],
  ["GET", "/user/v1/job/get-by-id/:id"],
  ["POST", "/user/v1/job-information/apply-outside/:id"],
  ["POST", "/user/v1/job-information/toggle-save-job/:id"],
  ["POST", "/user/v1/job-information/rate-job/:id"],
  ["POST", "/user/v1/job-information/review-job/:id"],
  ["POST", "/user/v1/job-information/report-job/:id"],
  ["GET", "/user/v1/applying-job/get"],
  ["GET", "/user/v1/applying-job/readiness/:id"],
  ["POST", "/user/v1/applying-job/insert/:id"],
  ["GET", "/user/v1/app/dashboard/overview"],

  ["GET", "/user/v1/company/get-files"],
  ["POST", "/user/v1/company/join-request"],
  ["POST", "/user/v1/company/upload-file"],
  ["POST", "/user/v1/company/delete-file"],

  ["GET", "/user/v1/notifications"],
  ["GET", "/user/v1/notifications/get"],
  ["GET", "/user/v1/notifications/unread-count"],
  ["POST", "/user/v1/notifications/read-all"],
  ["PATCH", "/user/v1/notifications/read-all"],
  ["POST", "/user/v1/notifications/:id/read"],
  ["PATCH", "/user/v1/notifications/:id/read"],
  ["DELETE", "/user/v1/notifications/:id"],
  ["POST", "/user/v1/notifications/:id/delete"],

  ["GET", "/notifications/v1/list"],
  ["GET", "/notifications/v1/unread-count"],
  ["POST", "/notifications/v1/read"],
  ["POST", "/notifications/v1/device-token"],
  ["DELETE", "/notifications/v1/device-token"],

  ["GET", "/user/v1/fcm/tokens"],
  ["POST", "/user/v1/fcm/tokens"],
  ["POST", "/user/v1/fcm/update-tokens/:id"],
  ["POST", "/user/v1/fcm/delete-tokens/:id"],

  ["GET", "/user/v1/campus/dashboard"],
  ["GET", "/user/v1/campus/dashboard/overview"],
  ["GET", "/user/v1/campus/overview"],
  ["GET", "/user/v1/campus/content"],
  ["GET", "/user/v1/campus/events"],
  ["GET", "/user/v1/campus/resources"],
  ["GET", "/user/v1/campus/universities"],
  ["GET", "/user/v1/campus/universities/:id/campuses"],
  ["GET", "/user/v1/campus/student-verifications/me"],
  ["POST", "/user/v1/campus/student-verifications"],
  ["POST", "/user/v1/campus/student-verifications/:id/resubmit"],
  ["POST", "/user/v1/campus/verification/start"],
  ["POST", "/user/v1/campus/verification/confirm-email"],
  ["POST", "/user/v1/campus/verification/upload-document"],
  ["GET", "/user/v1/campus/admin/verifications"],
  ["POST", "/user/v1/campus/admin/verifications/:id/approve"],
  ["POST", "/user/v1/campus/admin/verifications/:id/reject"],
  ["POST", "/user/v1/campus/admin/verifications/:id/request-info"],
  ["GET", "/user/v1/campus/profile"],
  ["POST", "/user/v1/campus/profile"],
  ["PUT", "/user/v1/campus/profile"],
  ["PATCH", "/user/v1/campus/profile"],
  ["GET", "/user/v1/campus/opportunities"],
  ["GET", "/user/v1/campus/opportunities/:id"],
  ["GET", "/user/v1/campus/opportunities/:id/readiness"],
  ["POST", "/user/v1/campus/opportunities/:id/apply"],
  ["POST", "/user/v1/campus/opportunities/:id/apply-external"],
  ["POST", "/user/v1/campus/opportunities/:id/save"],
  ["DELETE", "/user/v1/campus/opportunities/:id/save"],
  ["POST", "/user/v1/campus/opportunities/:id/toggle-save"],
  ["GET", "/user/v1/campus/applications"],
  ["GET", "/user/v1/campus/applications/:id"],
  ["POST", "/user/v1/campus/applications/:id/messages"],
  ["PATCH", "/user/v1/campus/applications/:id/cancel"],
  ["POST", "/user/v1/campus/applications/:id/cancel"],
  ["POST", "/user/v1/campus/events/:eventId/register"],
  ["PATCH", "/user/v1/campus/events/:eventId/cancel"],
  ["POST", "/user/v1/campus/events/:eventId/cancel"],

  ["GET", "/employee/v1/global/jobs"],
  ["GET", "/employee/v1/global/jobs/recommended"],
  ["GET", "/employee/v1/global/jobs/saved"],
  ["GET", "/employee/v1/global/jobs/:jobId"],
  ["POST", "/employee/v1/global/jobs/:jobId/apply"],
  ["POST", "/employee/v1/global/jobs/:jobId/save"],
  ["DELETE", "/employee/v1/global/jobs/:jobId/save"],
  ["POST", "/employee/v1/global/jobs/:jobId/rate"],
  ["POST", "/employee/v1/global/jobs/:jobId/review"],
  ["GET", "/employee/v1/global/applications"],
  ["GET", "/employee/v1/global/applications/interviews"],
  ["PATCH", "/employee/v1/global/applications/interviews/:interviewId/respond"],
  ["GET", "/employee/v1/global/applications/offers"],
  ["PATCH", "/employee/v1/global/applications/offers/:invitationId/respond"],
  ["GET", "/employee/v1/global/applications/:applicationId"],
  ["POST", "/employee/v1/global/applications/:applicationId/messages"],
  ["PATCH", "/employee/v1/global/applications/:applicationId/cancel"],
  ["GET", "/employee/v1/global/companies"],
  ["GET", "/employee/v1/global/companies/activity"],
  ["GET", "/employee/v1/global/companies/applied"],
  ["GET", "/employee/v1/global/companies/saved-jobs"],
  ["GET", "/employee/v1/global/companies/viewed"],
  ["GET", "/employee/v1/global/companies/:companyId"],
  ["POST", "/employee/v1/global/companies/:companyId/review"],
  ["GET", "/employee/v1/global/profile"],
  ["PUT", "/employee/v1/global/profile"],
  ["PUT", "/employee/v1/global/profile/about-me"],
  ["PUT", "/employee/v1/global/profile/work-preferences"],
  ["GET", "/employee/v1/global/profile/:section"],
  ["PUT", "/employee/v1/global/profile/:section"],
  ["POST", "/employee/v1/global/profile/:section"],
  ["PATCH", "/employee/v1/global/profile/:section/:itemId"],
  ["DELETE", "/employee/v1/global/profile/:section/:itemId"],

  ["GET", "/employee/v1/cv/uploaded"],
  ["POST", "/employee/v1/cv/upload"],
  ["PUT", "/employee/v1/cv/upload/:cvId"],
  ["DELETE", "/employee/v1/cv/uploaded/:cvId"],
  ["GET", "/employee/v1/cv/generate/templates"],
  ["POST", "/employee/v1/cv/generate/download-url"],

  ["POST", "/company/v1/auth/login"],
  ["GET", "/company/v1/global"],
  ["GET", "/company/v1/global/profile"],
  ["PUT", "/company/v1/global/profile"],
  ["GET", "/company/v1/global/me/basic-profile"],
  ["PUT", "/company/v1/global/me/basic-profile"],
  ["PUT", "/company/v1/global/me/image"],
  ["POST", "/company/v1/global/profile/rebuild-search-filters"],
  ["PUT", "/company/v1/global/profile/about"],
  ["PUT", "/company/v1/global/profile/contact"],
  ["PUT", "/company/v1/global/profile/location"],
  ["PUT", "/company/v1/global/profile/media"],
  ["GET", "/company/v1/global/profile/files"],
  ["POST", "/company/v1/global/profile/files"],
  ["DELETE", "/company/v1/global/profile/files/:filename"],
  ["GET", "/company/v1/global/profile/files/:filename/download"],
  ["GET", "/company/v1/global/profile/:section"],
  ["POST", "/company/v1/global/profile/:section"],
  ["PATCH", "/company/v1/global/profile/:section/:itemId"],
  ["DELETE", "/company/v1/global/profile/:section/:itemId"],

  ["GET", "/company/v1/global/subscription/current"],
  ["GET", "/company/v1/global/subscription/billing-summary"],
  ["GET", "/company/v1/global/subscription/invoices"],
  ["GET", "/company/v1/global/subscription/invoices/:invoiceId"],
  ["POST", "/company/v1/global/subscription/request"],

  ["GET", "/company/v1/campus/overview"],
  ["GET", "/company/v1/campus/opportunities"],
  ["POST", "/company/v1/campus/opportunities"],
  ["GET", "/company/v1/campus/students"],
  ["GET", "/company/v1/campus/partners"],
  ["POST", "/company/v1/campus/partners"],

  ["GET", "/company/v1/global/audit-logs"],
  ["GET", "/company/v1/global/jobs/:jobId/audit-logs"],
  ["GET", "/company/v1/global/applications/:applicationId/audit-logs"],

  ["GET", "/company/v1/global/jobs"],
  ["POST", "/company/v1/global/jobs"],
  ["PATCH", "/company/v1/global/jobs/bulk"],
  ["GET", "/company/v1/global/jobs/:jobId"],
  ["PUT", "/company/v1/global/jobs/:jobId"],
  ["DELETE", "/company/v1/global/jobs/:jobId"],
  ["GET", "/company/v1/global/jobs/:jobId/applicants"],
  ["GET", "/company/v1/global/jobs/:jobId/recommended-employees"],
  ["PATCH", "/company/v1/global/jobs/:jobId/publish"],
  ["PATCH", "/company/v1/global/jobs/:jobId/pause"],
  ["PATCH", "/company/v1/global/jobs/:jobId/archive"],
  ["PATCH", "/company/v1/global/jobs/:jobId/restore"],
  ["POST", "/company/v1/global/jobs/:jobId/clone"],

  ["GET", "/company/v1/global/applications"],
  ["GET", "/company/v1/global/applications/:applicationId"],
  ["PATCH", "/company/v1/global/applications/:applicationId/status"],
  ["POST", "/company/v1/global/applications/:applicationId/note"],
  ["POST", "/company/v1/global/applications/:applicationId/rate"],
  ["PATCH", "/company/v1/jobs/hiring/applications/:applicationId/restore"],
  ["POST", "/company/v1/jobs/hiring/applications/:applicationId/messages"],
  ["PATCH", "/company/v1/jobs/hiring/applications/:applicationId/block-applicant"],
  ["GET", "/company/v1/jobs/hiring/applications/:applicationId/cv"],
  ["POST", "/company/v1/jobs/hiring/applications/bulk-cv"],
  ["POST", "/company/v1/jobs/hiring/applications/bulk-export"],

  ["GET", "/company/v1/global/interviews"],
  ["POST", "/company/v1/global/interviews"],
  ["PATCH", "/company/v1/global/interviews/:interviewId"],
  ["DELETE", "/company/v1/global/interviews/:interviewId"],

  ["GET", "/company/v1/global/support-tickets"],
  ["POST", "/company/v1/global/support-tickets"],
  ["GET", "/company/v1/global/support-tickets/:ticketId"],
  ["POST", "/company/v1/global/support-tickets/:ticketId/messages"],

  ["GET", "/company/v1/global/members"],
  ["POST", "/company/v1/global/members"],
  ["PATCH", "/company/v1/global/members/:memberId"],
  ["DELETE", "/company/v1/global/members/:memberId"],

  ["GET", "/company/v1/global/question-library"],
  ["POST", "/company/v1/global/question-library"],
  ["PATCH", "/company/v1/global/question-library/:questionId"],
  ["DELETE", "/company/v1/global/question-library/:questionId"],
  ["GET", "/company/v1/global/message-templates"],
  ["POST", "/company/v1/global/message-templates"],
  ["PATCH", "/company/v1/global/message-templates/:templateId"],
  ["DELETE", "/company/v1/global/message-templates/:templateId"],

  ["GET", "/company/v1/global/analytics"],
  ["GET", "/company/v1/global/analytics/jobs"],
  ["GET", "/company/v1/global/analytics/applications"],
  ["GET", "/company/v1/global/analytics/profile"],
  ["GET", "/company/v1/jobs/hiring/summary"],
  ["GET", "/company/v1/jobs/hiring/pipeline"],
  ["GET", "/company/v1/jobs/hiring/talent-pool"],
  ["GET", "/company/v1/jobs/hiring/invitations"],
  ["GET", "/company/v1/jobs/hiring/invitations/:invitationId"],
  ["POST", "/company/v1/jobs/hiring/:jobId/invitations"],
  ["PATCH", "/company/v1/jobs/hiring/invitations/:invitationId/cancel"],
  ["GET", "/company/v1/jobs/hiring/reviews"],
  ["GET", "/company/v1/jobs/talent/employees"],
  ["GET", "/company/v1/jobs/talent/employees/:employeeId"],
  ["GET", "/company/v1/jobs/talent/:jobId/smart-employees"],
  ["POST", "/company/v1/jobs/talent/:jobId/smart-employees/generate"],
  ["GET", "/company/v1/jobs/talent/:jobId/employees/:employeeId/match"],
  ["GET", "/company/v1/jobs/talent/help-requests"],
  ["POST", "/company/v1/jobs/talent/help-requests"],
  ["POST", "/company/v1/jobs/talent/:jobId/help-requests"],
  ["GET", "/company/v1/jobs/talent/help-requests/:requestId"],
  ["PATCH", "/company/v1/jobs/talent/help-requests/:requestId/cancel"],
];

const requiredCampusStudentPaths = [
  "/user/v1/campus/dashboard",
  "/user/v1/campus/dashboard/overview",
  "/user/v1/campus/overview",
  "/user/v1/campus/content",
  "/user/v1/campus/events",
  "/user/v1/campus/resources",
  "/user/v1/campus/profile",
  "/user/v1/campus/opportunities",
  "/user/v1/campus/opportunities/:id",
  "/user/v1/campus/opportunities/:id/readiness",
  "/user/v1/campus/opportunities/:id/apply",
  "/user/v1/campus/opportunities/:id/apply-external",
  "/user/v1/campus/opportunities/:id/save",
  "/user/v1/campus/opportunities/:id/toggle-save",
  "/user/v1/campus/applications",
  "/user/v1/campus/applications/:id",
  "/user/v1/campus/applications/:id/messages",
  "/user/v1/campus/applications/:id/cancel",
  "/user/v1/campus/events/:eventId/register",
  "/user/v1/campus/events/:eventId/cancel",
];

const requiredUniversityAdminPaths = [
  "/campus/v1/admin/verifications",
  "/campus/v1/admin/verifications/:id/approve",
  "/campus/v1/admin/verifications/:id/reject",
  "/campus/v1/admin/verifications/:id/request-info",
  "/university/v1/dashboard",
  "/university/v1/dashboard/overview",
  "/university/v1/overview",
  "/university/v1/students",
  "/university/v1/students/:studentId/career-passport",
  "/university/v1/verifications",
  "/university/v1/verifications/:id/approve",
  "/university/v1/verifications/:id/reject",
  "/university/v1/verifications/:id/request-info",
  "/university/v1/analytics/employability",
  "/university/v1/reports/outcomes",
  "/university/v1/partners",
  "/university/v1/employer-partners",
  "/university/v1/opportunities",
  "/user/v1/campus/admin/verifications",
  "/user/v1/campus/admin/verifications/:id/approve",
  "/user/v1/campus/admin/verifications/:id/reject",
  "/user/v1/campus/admin/verifications/:id/request-info",
  "/user/v1/campus/university/overview",
  "/user/v1/campus/university/opportunities",
  "/user/v1/campus/university/students",
  "/user/v1/campus/university/partners",
];

function hasEndpoint(method, path) {
  return endpointByPath.get(path)?.methods.includes(method) === true;
}

const missingEndpoints = requiredEndpoints
  .filter(([method, path]) => !hasEndpoint(method, path))
  .map(([method, path]) => `${method} ${path}`);

assert.deepEqual(missingEndpoints, [], "Express app is missing mobile endpoints");

const missingCampusGuards = requiredCampusStudentPaths.filter((path) => {
  const middlewares = endpointByPath.get(path)?.middlewares || [];
  return !middlewares.includes("authUser") || !middlewares.includes("requireCampusStudent");
});

assert.deepEqual(missingCampusGuards, [], "Campus mobile endpoints must require a signed-in campus student");

const missingUniversityAdminGuards = requiredUniversityAdminPaths.filter((path) => {
  const middlewares = endpointByPath.get(path)?.middlewares || [];
  return !middlewares.includes("authUser") || !middlewares.includes("activeContextGuard");
});

assert.deepEqual(
  missingUniversityAdminGuards,
  [],
  "University admin mobile endpoints must require an active university_admin or super_admin context"
);

const sharedCareerPassportEndpoint = endpointByPath.get("/user/v1/career-passport/share/:token");
assert.ok(
  sharedCareerPassportEndpoint?.methods.includes("GET"),
  "Shared Career Passport token endpoint must be mounted"
);
assert.ok(
  !sharedCareerPassportEndpoint.middlewares.includes("authUser"),
  "Shared Career Passport token endpoint must stay public and token-gated"
);

console.log(`Mobile route mounts verified (${requiredEndpoints.length} method/path checks).`);
